# Generated by Django 5.2 on 2025-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.CharField(max_length=255),
        ),
    ]
