# Generated by Django 5.2 on 2025-05-25 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="postal_code",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid US ZIP code (e.g., 12345 or 12345-6789).",
                        regex="^\\d{5}(-\\d{4})?$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("name", "address_line1", "city", "state", "postal_code"),
                name="unique_location_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("name", "city"), name="unique_location_name_per_city"
            ),
        ),
    ]
