"""
Django settings for retrack project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# load_dotenv base directory
base_path = Path()
basedir = str(base_path.cwd())
# Load the environment variables
env = base_path.cwd() / ".env"
load_dotenv(env)

SECRET_KEY = os.getenv("SECRET_KEY")
POSTGRES_PASS = os.getenv("POSTGRES_PASS")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "debug_toolbar",
    "apps.core",
    "apps.shipments",
    "apps.attachments",
    "apps.locations",
    "apps.tracking",
    "phonenumber_field",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = "retrack.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "retrack.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "retrack",
        "USER": "postgres",
        "PASSWORD": f"{POSTGRES_PASS}",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Chicago"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "core.User"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

UNFOLD = {
    "SITE_HEADER": "ReTrackLogistics",
    "SITE_SYMBOL": "satellite_alt",  # symbol from icon set
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Users & Groups"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:core_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Attachments"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": _("Documents"),
                        "icon": "docs",
                        "link": reverse_lazy("admin:attachments_attachment_changelist"),
                    },
                ],
            },
            {
                "title": _("Operations"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": "Shipments",
                        "icon": "delivery_truck_speed",
                        "link": reverse_lazy("admin:shipments_shipment_changelist"),
                    },
                    {
                        "title": "Shipment Items",
                        "icon": "package_2",
                        "link": reverse_lazy("admin:shipments_shipmentitem_changelist"),
                    },
                ],
            },
            {
                "title": _("Tracking"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": "GPS Devices",
                        "icon": "sensors",
                        "link": reverse_lazy("admin:tracking_gpsdevice_changelist"),
                    },
                    {
                        "title": "GPS Pings",
                        "icon": "pin_drop",
                        "link": reverse_lazy(
                            "admin:tracking_gpstrackingping_changelist"
                        ),
                    },
                    {
                        "title": "Tracking Events",
                        "icon": "monitor_heart",
                        "link": reverse_lazy(
                            "admin:tracking_gpstrackingevent_changelist"
                        ),
                    },
                    {
                        "title": "Shipment Events",
                        "icon": "calendar_month",
                        "link": reverse_lazy(
                            "admin:shipments_shipmentstatusevent_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Resources"),
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": "Carriers",
                        "icon": "emoji_transportation",
                        "link": reverse_lazy("admin:shipments_carrier_changelist"),
                    },
                    {
                        "title": "Carrier Contacts",
                        "icon": "support_agent",
                        "link": reverse_lazy(
                            "admin:shipments_carriercontact_changelist"
                        ),
                    },
                    {
                        "title": "Drivers",
                        "icon": "id_card",
                        "link": reverse_lazy("admin:shipments_driver_changelist"),
                    },
                    {
                        "title": "Vehicles",
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:shipments_vehicle_changelist"),
                    },
                ],
            },
            {
                "title": "Reference Data",
                "separator": True,  # Top border
                "collapsible": True,  # Collapsible group of links
                "items": [
                    {
                        "title": "Locations",
                        "icon": "map",
                        "link": reverse_lazy("admin:locations_location_changelist"),
                    },
                    {
                        "title": "Assets",
                        "icon": "inventory",
                        "link": reverse_lazy("admin:shipments_asset_changelist"),
                    },
                ],
            },
        ],
    },
}
