# Generated by Django 5.2 on 2025-05-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="slug",
            field=models.SlugField(default="-"),
        ),
    ]
