# Generated by Django 5.2 on 2025-05-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_shipment_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="slug",
        ),
    ]
