# Generated by Django 5.2 on 2025-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0003_remove_shipment_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="slug",
            field=models.SlugField(default="-"),
            preserve_default=False,
        ),
    ]
