# Generated by Django 5.2 on 2025-05-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0004_shipment_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrier",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="shipmentstatusevent",
            name="notes",
        ),
    ]
