# Generated by Django 5.2 on 2025-05-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0005_alter_carrier_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="mc_number",
            field=models.CharField(default="-", max_length=50),
            preserve_default=False,
        ),
    ]
