# Generated by Django 5.2 on 2025-05-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0006_alter_carrier_mc_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="slug",
        ),
    ]
