# Generated by Django 5.2 on 2025-05-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0007_remove_shipment_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField()),
                (
                    "weight_lb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight of a single unit in pounds",
                        max_digits=7,
                    ),
                ),
                (
                    "length_in",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Length of the item in inches",
                        max_digits=7,
                    ),
                ),
                (
                    "width_in",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Width of the item in inches",
                        max_digits=7,
                    ),
                ),
                (
                    "height_in",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Height of the item in inches",
                        max_digits=7,
                    ),
                ),
                ("is_fragile", models.BooleanField(default=False)),
                ("is_hazardous", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_weight_lb",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight per unit in pounds",
                        max_digits=7,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_items",
                        to="shipments.asset",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipments.shipment",
                    ),
                ),
            ],
        ),
    ]
