# Generated by Django 5.2 on 2025-05-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0008_asset_shipmentitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="current_status",
        ),
    ]
