# Generated by Django 5.2 on 2025-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0009_remove_shipment_current_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carriercontact",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("DISPATCH", "Dispatch"),
                    ("BILLING", "Billing"),
                    ("SAFETY", "Safety"),
                ],
                default="DISPATCH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
