# Generated by Django 5.2 on 2025-05-17 12:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0010_alter_carriercontact_role_alter_driver_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carriercontact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="US"
            ),
        ),
    ]
