# Generated by Django 5.2 on 2025-05-17 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0012_alter_driver_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="plate_number",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid plate number using letters, numbers, or hyphens only (no spaces or special characters).",
                        regex="^[A-Za-z0-9-]{1,20}$",
                    )
                ],
            ),
        ),
    ]
