# Generated by Django 5.2 on 2025-05-17 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0013_alter_vehicle_plate_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="height_in",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Height of the item in inches",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="length_in",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Length of the item in inches",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="weight_lb",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Weight of a single unit in pounds",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="width_in",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Width of the item in inches",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
