# Generated by Django 5.2 on 2025-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0014_alter_asset_height_in_alter_asset_length_in_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipmentstatusevent",
            options={"ordering": ["event_timestamp"]},
        ),
        migrations.AddConstraint(
            model_name="shipmentstatusevent",
            constraint=models.UniqueConstraint(
                fields=("shipment", "status", "event_timestamp"),
                name="unique_status_event_per_timestamp",
            ),
        ),
    ]
