# Generated by Django 5.2 on 2025-05-17 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0015_alter_shipmentstatusevent_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"ordering": ["scheduled_pickup"]},
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="unit_weight_lb",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Weight per unit in pounds",
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
