# Generated by Django 5.2 on 2025-05-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        (
            "shipments",
            "0016_alter_shipment_options_alter_shipmentitem_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments_destination_temp",
                to="locations.location",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments_origin_temp",
                to="locations.location",
            ),
        ),
    ]
