# Generated by Django 5.2 on 2025-05-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0017_shipment_destination_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="origin",
        ),
    ]
