# Generated by Django 5.2 on 2025-05-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("shipments", "0018_remove_shipment_destination_remove_shipment_origin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="destination_location",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="origin_location",
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments_destination",
                to="locations.location",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments_origin",
                to="locations.location",
            ),
            preserve_default=False,
        ),
    ]
