# Generated by Django 5.2 on 2025-05-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0020_vehicle_gps_device"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="device_id",
        ),
    ]
