# Generated by Django 5.2 on 2025-05-24 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0021_remove_vehicle_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="gps_device",
        ),
    ]
