# Generated by Django 5.2 on 2025-05-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0022_remove_vehicle_gps_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carriercontact",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="shipments.carrier",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drivers",
                to="shipments.carrier",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentstatusevent",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_events",
                to="shipments.shipment",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="carrier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="shipments.carrier",
            ),
        ),
    ]
