# Generated by Django 5.2 on 2025-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0023_alter_carriercontact_carrier_alter_driver_carrier_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="carrier",
            constraint=models.UniqueConstraint(
                fields=("name", "mc_number"),
                name="unique_carrier_name_and_mc_number",
                violation_error_message="A carrier with this name and MC number already exists.",
            ),
        ),
    ]
