# Generated by Django 5.2 on 2025-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0024_carrier_unique_carrier_name_and_mc_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="carriercontact",
            constraint=models.UniqueConstraint(
                fields=("carrier", "first_name", "last_name"),
                name="unique_contact_name_per_carrier",
            ),
        ),
    ]
