# Generated by Django 5.2 on 2025-06-01 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0025_carriercontact_unique_contact_name_per_carrier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carriercontact",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format: 832-123-4567 or 8321234567",
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a 10-digit phone number in format 555-123-4567 or 5551234567.",
                        regex="^\\d{3}-?\\d{3}-?\\d{4}$",
                    )
                ],
            ),
        ),
    ]
