# Generated by Django 5.2 on 2025-06-11 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0026_alter_carriercontact_phone_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="carriercontact",
            name="unique_contact_name_per_carrier",
        ),
    ]
