# Generated by Django 5.2 on 2025-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0027_remove_carriercontact_unique_contact_name_per_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentstatusevent",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Optional notes about this status event.",
                max_length=500,
                null=True,
            ),
        ),
    ]
