# Generated by Django 5.2 on 2025-06-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0028_shipmentstatusevent_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="mc_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
