# Generated by Django 5.2 on 2025-06-15 13:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0030_alter_driver_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
