# Generated by Django 5.2 on 2025-06-18 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0032_asset_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="sku",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SKU must be in the format 'AST' followed by 4 digits (e.g., AST0001).",
                        regex="^AST\\d{4}$",
                    )
                ],
            ),
        ),
    ]
