# Generated by Django 5.2 on 2025-06-18 12:31

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0033_alter_asset_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="sku",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SKU must be in the format 'AST' followed by 4 digits (e.g., AST0001).",
                        regex="^AST\\d{4}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("sku"), name="unique_upper_sku"
            ),
        ),
    ]
