# Generated by Django 5.2 on 2025-06-19 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0034_alter_asset_sku_asset_unique_upper_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="sku",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="SKU must be in the format 'AST' followed by 4 digits (e.g., AST0001).",
                        regex="^[aA][sS][tT]\\d{4}$",
                    )
                ],
            ),
        ),
    ]
