# Generated by Django 5.2 on 2025-06-19 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0035_alter_asset_sku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="mc_number",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="MC number must be in the format 'MC' followed by 6 digits (e.g., MC123456).",
                        regex="^MC\\d{6}$",
                    )
                ],
            ),
        ),
    ]
