# Generated by Django 5.2 on 2025-06-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0036_alter_carrier_mc_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="carrier",
            name="unique_carrier_name_and_mc_number",
        ),
    ]
