# Generated by Django 5.2 on 2025-06-21 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0038_shipmentitem_created_at_shipmentitem_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentitem",
            name="unit_weight_lb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight per unit in pounds",
                max_digits=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
