# Generated by Django 5.2 on 2025-07-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0039_alter_shipmentitem_unit_weight_lb"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="created_by_system",
            field=models.CharField(
                choices=[
                    ("CRM System", "CRM System"),
                    ("Manual Entry", "Manual Entry"),
                    ("Partner API", "Partner API"),
                    ("Legacy Migration", "Legacy Migration"),
                ],
                default="Manual Entry",
                help_text="Source system or method that created this record",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrier",
            name="external_id",
            field=models.CharField(
                default="-",
                editable=False,
                help_text="System-generated UUID with a source-specific prefix (e.g., CRM_, API_, etc.)",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrier",
            name="mc_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="carrier",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Suspended", "Suspended"),
                    ("Terminated", "Terminated"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
