# Generated by Django 5.2 on 2025-07-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0040_carrier_created_by_system_carrier_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrier",
            name="external_id",
            field=models.CharField(
                editable=False,
                help_text="System-generated UUID with a source-specific prefix (e.g., CRM_, API_, etc.)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
