# Generated by Django 5.2 on 2025-07-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0041_alter_carrier_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this record was soft-deleted.",
                null=True,
            ),
        ),
    ]
