# Generated by Django 5.2 on 2025-05-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("shipments", "0019_remove_shipment_destination_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPSDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is the device currently active?"
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last received ping.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vehicle currently using this GPS device.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gps_devices",
                        to="shipments.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPSTrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("arrived", "Arrived"),
                            ("departed", "Departed"),
                            ("stopped", "Stopped"),
                            ("in_transit", "In Transit"),
                            ("custom", "Custom"),
                        ],
                        help_text="Classified type of tracking event.",
                        max_length=20,
                    ),
                ),
                (
                    "event_timestamp",
                    models.DateTimeField(help_text="When the event occurred."),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional context or explanation."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gps_device",
                    models.ForeignKey(
                        help_text="Device responsible for this tracking event.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="tracking.gpsdevice",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional known location or geofence involved.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="locations.location",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional shipment related to the tracking event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipments.shipment",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vehicle involved at the time of the event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shipments.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="GPSTrackingPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Latitude at time of ping.",
                        max_digits=9,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Longitude at time of ping.",
                        max_digits=9,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Timestamp of the GPS reading."),
                ),
                (
                    "speed_mph",
                    models.FloatField(
                        blank=True,
                        help_text="Optional. Speed at time of ping.",
                        null=True,
                    ),
                ),
                (
                    "heading",
                    models.FloatField(
                        blank=True,
                        help_text="Optional. Direction of movement in degrees.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gps_device",
                    models.ForeignKey(
                        help_text="The GPS device that generated this ping.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pings",
                        to="tracking.gpsdevice",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["gps_device", "timestamp"],
                        name="tracking_gp_gps_dev_a639b5_idx",
                    )
                ],
            },
        ),
    ]
