# Generated by Django 5.2 on 2025-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gpstrackingping",
            options={"ordering": ["-recorded_at"]},
        ),
        migrations.RemoveIndex(
            model_name="gpstrackingping",
            name="tracking_gp_gps_dev_a639b5_idx",
        ),
        migrations.RenameField(
            model_name="gpstrackingping",
            old_name="timestamp",
            new_name="recorded_at",
        ),
        migrations.AddIndex(
            model_name="gpstrackingping",
            index=models.Index(
                fields=["gps_device", "recorded_at"],
                name="tracking_gp_gps_dev_52c08e_idx",
            ),
        ),
    ]
