# Generated by Django 5.2 on 2025-05-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_alter_gpstrackingping_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gpsdevice",
            old_name="device_id",
            new_name="serial_number",
        ),
    ]
