# Generated by Django 5.2 on 2025-05-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_rename_device_id_gpsdevice_serial_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gpstrackingping",
            constraint=models.UniqueConstraint(
                fields=("gps_device", "recorded_at"),
                name="unique_ping_per_device_timestamp",
            ),
        ),
    ]
