# Generated by Django 5.2 on 2025-05-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_alter_location_postal_code_and_more"),
        ("shipments", "0022_remove_vehicle_gps_device"),
        ("tracking", "0004_gpstrackingping_unique_ping_per_device_timestamp"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gpstrackingevent",
            constraint=models.UniqueConstraint(
                fields=("gps_device", "event_type", "event_timestamp"),
                name="unique_tracking_event_per_timestamp",
            ),
        ),
    ]
